global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: backend
    metrics_path: /prometheus
    static_configs:
      - targets:
          - "cougarcs-backend-production.up.railway.app"
